server:
  port: 8080

spring:
  application:
    name: api-gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  cloud:
    gateway:
      # Bật auto-discovery route từ Eureka
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    # Chỉ dùng khi chạy local, nếu deploy nhiều máy nên để hostname
    ip-address: 127.0.0.1
    hostname: localhost

springdoc:
  swagger-ui:
    urls:
      - name: auth-service
        url: http://localhost:8081/v3/api-docs
      - name: user-service
        url: http://localhost:8082/v3/api-docs
      - name: cinema-service
        url: http://localhost:8083/v3/api-docs
      - name: movie-service
        url: http://localhost:8084/v3/api-docs
      - name: media-service
        url: http://localhost:8085/v3/api-docs

minhnb:
  jwt:
    base64-secret: Muw9kQMoEFTnfKm5sHbvqus3GvSYF4mSCL3ay11sjkRGLpMnvBTpsRF/bDHZmuI5ROhJ23QuZhOb1Cx3OZxy0w==
    access-token-validity-in-seconds: 1800
    refresh-token-validity-in-seconds: 2592000

