server:
  port: 8085

minio:
  url: http://127.0.0.1:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: cinema-assets

spring:
  application:
    name: media-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true      # Dùng IP thay vì hostname
    ip-address: 127.0.0.1