server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  client:
    register-with-eureka: false   # Không tự đăng ký chính nó
    fetch-registry: false         # Không đi lấy danh sách service khác
